"""Контракт хранилища отделяет операции с сессиями от конкретной базы данных."""

from datetime import datetime
from typing import Protocol

from local_agent.sessions.models import Session


class SessionRepository(Protocol):
    def save(self, session: Session) -> Session: ...

    def update(self, session: Session) -> Session: ...

    def rename(self, session_id: str, title: str, only_if_default: bool) -> Session | None: ...

    def patch(self, session_id: str, updates: dict[str, object]) -> Session | None: ...

    def delete(self, session_id: str) -> bool: ...

    def set_usage(self, session_id: str, usage: dict[str, object]) -> None: ...

    def touch(self, session_id: str, updated_at: datetime) -> None: ...

    def get(self, session_id: str) -> Session | None: ...

    def list(self) -> list[Session]: ...
